version: 2

project_name: acs

builds:
  - id: acs
    main: ./cmd/acs
    binary: acs
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -X main.releaseVersion=v{{ .Version }}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: acs
    ids:
      - acs
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      mode: 0755
      owner: root
      group: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          mode: 0644
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          mode: 0644
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

checksum:
  name_template: SHA256SUMS
  algorithm: sha256

snapshot:
  version_template: "{{ .Env.ACS_RELEASE_VERSION }}"

changelog:
  disable: true

release:
  disable: true
